name:                backend
version:             0.1.0.0
dependencies:
- base >= 4.7 && < 5
- scotty
- acid-state
- safecopy
- aeson
- text
- mtl
- transformers
- wai
- wai-cors
- wai-extra
- network
- warp
- http-types
- containers
- lens
- uuid
- base64-bytestring
- bytestring
- binary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
