name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: "9.4.7"
        enable-stack: true
        stack-version: "3.3.1"

    - name: Build executable
      run: |
        stack build --copy-bins
        cp /home/runner/.local/bin/backend-exe $GITHUB_WORKSPACE/backend-exe
      working-directory: backend

    - name: Upload via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_SSH_KEY }}
        source: "backend-exe"
        target: "/home/ubuntu/"

    - name: Restart backend
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USER }}
        key: ${{ secrets.BACKEND_SSH_KEY }}
        script: |
          sudo systemctl restart meetr-backend
